database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "ServBay.dev"
  database: "kodbox"
  charset: "utf8mb4"

server:
  port: 8080
  domain: "http://127.0.0.1:8080"  # 客户端域名，用于重定向

kodbox:
  domain: "http://kodbox.test"

# 错误页面配置
error:
  not_found_page: "/error/not-found.html" 