name: Release Package

on:
  release:
    types: [published]

jobs:
  release:
    name: Create and Upload Release Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release folder
        run: |
          mkdir -p release
          # Copy client binaries
          cp artifacts/client-*/smart-finder-client-* release/ || true
          # Copy gateway binaries
          cp artifacts/gateway-*/smart-finder-gateway-* release/ || true
          # Copy configuration files
          cp gateway/config/config.yaml release/ || true
          cp gateway/public/error/not-found.html release/ || true
          # Create README for release
          cat > release/README.md << 'EOF'
          # Smart Finder Release
          
          ## 兼容性说明
          本版本使用静态链接构建，支持以下系统：
          - CentOS 7+ / RHEL 7+
          - Ubuntu 16.04+
          - Debian 9+
          - Windows 7+
          - macOS 10.12+
          
          ## 客户端 (Client)
          - smart-finder-client-linux-amd64: Linux x64 版本 (兼容CentOS 7)
          - smart-finder-client-windows-amd64.exe: Windows x64 版本
          - smart-finder-client-darwin-amd64: macOS Intel 版本
          - smart-finder-client-darwin-arm64: macOS Apple Silicon 版本
          
          ## 服务端 (Gateway)
          - smart-finder-gateway-linux-amd64: Linux x64 版本 (兼容CentOS 7)
          - smart-finder-gateway-windows-amd64.exe: Windows x64 版本
          - smart-finder-gateway-darwin-amd64: macOS Intel 版本
          - smart-finder-gateway-darwin-arm64: macOS Apple Silicon 版本
          
          ## 使用说明
          1. 根据您的操作系统选择对应的可执行文件
          2. 确保配置文件 config.yaml 在同一目录下
          3. 运行服务端: ./smart-finder-gateway-[platform]-[arch]
          4. 运行客户端: ./smart-finder-client-[platform]-[arch]
          
          ## CentOS 7 特别说明
          本版本已针对CentOS 7进行了优化，使用静态链接避免依赖问题。
          如果遇到权限问题，请使用: chmod +x smart-finder-*
          EOF

      - name: Create release zip
        run: |
          cd release
          zip -r ../smart-finder-${{ github.event.release.tag_name }}.zip .

      - name: Upload release asset to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: smart-finder-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 